spring:
  application:
    name: customer-service
  config:
    import: "optional:configserver:http://localhost:9205"
  datasource:
    password: 654321
    url: jdbc:mysql://localhost:3306/customer_service?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non-null
 
server:
  port: 9202

#  boot:
#    admin:
#      client:
#        url:
#        - http://localhost:9200
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  endpoints:
#    web:
#      exposure:
#        include:
#        - "*"  
#  info:
#    env:
#      enabled: true